services:
  web:
    build: .
    pull_policy: always
    ports:
      - "${APP_PORT}:80"
    depends_on:
      - db
    env_file:
      - .env.prod
    container_name: vide-ton-cube-web-prod
    environment: 
      APP_ENV: ${APP_ENV}
      DB_CONNECTION: ${DB_CONNECTION}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}

  db:
    image: mysql:8.0
    restart: always
    ports:
      - "${DB_PORT}:3308"
    env_file:
      - .env.prod
    container_name: vide-ton-cube-db-prod
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - db-data-prod:/var/lib/mysql
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
      
volumes:
  db-data-prod: