services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "${APP_PORT}:80"
    depends_on:
      - db
    env_file:
      - .env.dev
    container_name: vide-ton-cube-web-dev
    volumes:
      - .:/var/www/html
    environment:
      APP_ENV: ${APP_ENV}
      DB_HOST: ${DB_HOST}
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_PORT: ${DB_PORT}

  db:
    image: mysql:8.0
    restart: always
    ports:
      - "${DB_PORT}:3307"
    env_file:
      - .env.dev 
    container_name: vide-ton-cube-db-dev
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE} 
      MYSQL_USER: ${MYSQL_USER}         
      MYSQL_PASSWORD: ${MYSQL_PASSWORD} 
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - db-data-dev:/var/lib/mysql
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  db-data-dev: